import { useEffect, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { blankIncident, downloadReport, incidentInput, incidentStatuses, isoTime, localTime, operationsApi, severities, type AlertDraft, type Incident, type IncidentInput, type OperationalEvent, type Option, type Options } from '../services/operations'

export function IncidentsPage(){
  const [params]=useSearchParams(),alertId=params.get('alert_id'),source=params.get('source')??'video'
  const [items,setItems]=useState<Incident[]>([]),[events,setEvents]=useState<OperationalEvent[]>([]),[options,setOptions]=useState<Options>({cameras:[],videos:[],sessions:[]})
  const [status,setStatus]=useState(''),[severity,setSeverity]=useState(''),[eventId,setEventId]=useState(params.get('event_id')??'')
  const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[setupError,setSetupError]=useState('')
  const [editing,setEditing]=useState<string|null>(null),[form,setForm]=useState<IncidentInput>(blankIncident),[selected,setSelected]=useState<Incident|null>(null),[alertNote,setAlertNote]=useState('')
  const filter=new URLSearchParams();if(status)filter.set('status',status);if(severity)filter.set('severity',severity);if(eventId)filter.set('event_id',eventId)
  const query=filter.size?`?${filter}`:''
  useEffect(()=>{let active=true;Promise.all([operationsApi<OperationalEvent[]>('/events'),operationsApi<Options>('/incidents/options')]).then(([e,o])=>{if(active){setEvents(e);setOptions(o)}}).catch(()=>{if(active)setSetupError('Unable to load context choices. Refresh to retry.')});return()=>{active=false}},[])
  useEffect(()=>{let active=true;setLoading(true);setError('');operationsApi<Incident[]>('/incidents'+query).then(data=>{if(active)setItems(data)}).catch(()=>{if(active)setError('Unable to load incidents.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[query])
  useEffect(()=>{if(!alertId)return;let active=true;operationsApi<AlertDraft>(`/incidents/alert-context?source=${encodeURIComponent(source)}&alert_id=${encodeURIComponent(alertId)}`).then(draft=>{if(active){const {context,...values}=draft;setForm({...blankIncident(),...values,occurred_at:draft.occurred_at||new Date().toISOString()});setEditing('new');setAlertNote(`Source alert: ${context.label}. Recorded ${context.recorded_at}.${context.video_offset_seconds==null?'':' Video offset: '+context.video_offset_seconds+' seconds. Video capture time is unknown; confirm the occurrence time.'}`)}}).catch(()=>{if(active)setSetupError('Unable to load source alert. It may have been deleted or is not accessible.')});return()=>{active=false}},[alertId,source])
  async function run(action:()=>Promise<unknown>){setBusy(true);setError('');try{await action();setItems(await operationsApi<Incident[]>('/incidents'+query))}catch(e){setError(e instanceof Error?e.message:'Unable to update incident')}finally{setBusy(false)}}
  function edit(item?:Incident){setEditing(item?.id??'new');setForm(item?incidentInput(item):{...blankIncident(),event_id:eventId||null});setAlertNote('')}
  function filterChange(setter:(value:string)=>void,value:string){setter(value);setLoading(true);setError('')}
  async function transition(item:Incident,status:IncidentInput['status']){await run(async()=>{const updated=await operationsApi<Incident>(`/incidents/${item.id}`,'PUT',{...incidentInput(item),status});if(selected?.id===item.id)setSelected(updated)})}
  return <div className="page operations-page"><div className="page-heading"><div><p className="eyebrow">OPERATOR WORKSPACE</p><h1>Incidents</h1><p>Human-authored operational records. An alert is context, not an automatically confirmed incident.</p></div><button className="primary" disabled={busy} onClick={()=>edit()}>Create incident</button></div>
    {setupError&&<p role="alert">{setupError}</p>}{error&&<p role="alert">{error}</p>}
    <div className="card operations-filters"><label>Filter status<select disabled={busy} value={status} onChange={e=>filterChange(setStatus,e.target.value)}><option value="">All statuses</option>{incidentStatuses.map(s=><option key={s}>{s}</option>)}</select></label><label>Filter severity<select disabled={busy} value={severity} onChange={e=>filterChange(setSeverity,e.target.value)}><option value="">All severities</option>{severities.map(s=><option key={s}>{s}</option>)}</select></label><label>Filter event<select disabled={busy} value={eventId} onChange={e=>filterChange(setEventId,e.target.value)}><option value="">All events</option>{eventId&&!events.some(e=>e.id===eventId)&&<option value={eventId}>{eventId}</option>}{events.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><button disabled={busy} onClick={()=>void run(()=>downloadReport(query))}>Download CSV</button></div>
    {editing&&<form className="card operations-form" aria-label="Incident form" onSubmit={e=>{e.preventDefault();void run(async()=>{const result=await operationsApi<Incident>(editing==='new'?'/incidents':`/incidents/${editing}`,editing==='new'?'POST':'PUT',form);setSelected(result);setEditing(null)})}}><h2>{editing==='new'?'New incident':'Edit incident'}</h2>{alertNote&&<p className="operations-source">{alertNote}</p>}
      <label>Title<input required maxLength={160} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Description<textarea maxLength={4000} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label>
      <label>Severity<select value={form.severity} onChange={e=>setForm({...form,severity:e.target.value as IncidentInput['severity']})}>{severities.map(s=><option key={s}>{s}</option>)}</select></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as IncidentInput['status']})}>{incidentStatuses.map(s=><option key={s}>{s}</option>)}</select></label>
      <label>Occurred at<input type="datetime-local" required value={localTime(form.occurred_at)} onChange={e=>setForm({...form,occurred_at:isoTime(e.target.value)})}/></label>
      <p className="analytics-note">Local time. Resolution time is recorded when resolved or closed; reopening clears it. Avoid personal or biometric details in notes.</p>
      <Choice label="Event" value={form.event_id} options={events.map(e=>({id:e.id,label:e.name}))} onChange={value=>setForm({...form,event_id:value})}/>
      <Choice label="Camera" value={form.camera_id} options={options.cameras} onChange={value=>setForm({...form,camera_id:value})}/><Choice label="Uploaded video" value={form.video_id} options={options.videos} onChange={value=>setForm({...form,video_id:value})}/><Choice label="Live session" value={form.live_session_id} options={options.sessions} onChange={value=>setForm({...form,live_session_id:value,camera_id:options.sessions.find(s=>s.id===value)?.camera_id??form.camera_id})}/>
      {(form.alert_event_id||form.live_alert_event_id)&&<p>Linked {form.alert_event_id?'video':'live'} alert: {form.alert_event_id??form.live_alert_event_id}. <button type="button" onClick={()=>{setForm({...form,alert_event_id:null,live_alert_event_id:null});setAlertNote('')}}>Remove alert link</button></p>}
      <div className="operations-actions"><button className="primary" disabled={busy||!form.title.trim()}>Save incident</button><button type="button" disabled={busy} onClick={()=>setEditing(null)}>Cancel</button></div>
    </form>}
    {loading?<p role="status">Loading incidents...</p>:!error&&!items.length?<article className="card"><h2>No incidents match</h2><p>Create an incident manually or use Create incident on a stored alert.</p></article>:null}
    <p className="analytics-note">Latest 200 matching incidents. CSV includes all matches, up to 10,000 rows. Context choices show the latest 200 resources.</p>
    <div className="operations-list">{items.map(item=><article className="card" key={item.id}><div className="section-title"><h2>{item.title}</h2><span>{item.severity} / {item.status}</span></div><p>{new Date(item.occurred_at).toLocaleString()} / {item.context.event?.label??'No event linked'}</p><div className="operations-actions"><button disabled={busy} onClick={()=>void run(async()=>setSelected(await operationsApi<Incident>(`/incidents/${item.id}`)))}>Details {item.title}</button><button disabled={busy} onClick={()=>edit(item)}>Edit {item.title}</button>{!['RESOLVED','CLOSED'].includes(item.status)&&<button disabled={busy} onClick={()=>void transition(item,'RESOLVED')}>Resolve {item.title}</button>}{item.status!=='CLOSED'&&<button disabled={busy} onClick={()=>void transition(item,'CLOSED')}>Close {item.title}</button>}</div></article>)}</div>
    {selected&&<section className="card operations-detail" aria-label="Incident detail"><div className="section-title"><h2>{selected.title}</h2><button onClick={()=>setSelected(null)}>Hide details</button></div><p>{selected.severity} / {selected.status}</p><p className="operations-description">{selected.description||'No description provided.'}</p><p>Occurred: {new Date(selected.occurred_at).toLocaleString()}</p><p>Resolved: {selected.resolved_at?new Date(selected.resolved_at).toLocaleString():'Not resolved'}</p><h3>Saved monitoring context</h3><p className="analytics-note">Labels reflect the time of linking and remain after source deletion. An absent reference means the source is no longer linked.</p>{Object.entries(selected.context).map(([key,value])=><div className="operations-context" key={key}><strong>{key.replaceAll('_',' ')}: {value.label}</strong><p>{value.rule_type} {value.severity} {value.zone}</p>{value.recorded_at&&<p>Alert recorded: {new Date(value.recorded_at).toLocaleString()}</p>}{value.video_offset_seconds!=null&&<p>Video offset: {value.video_offset_seconds} s</p>}<small>Original reference: {value.id} / {selected[(key==='alert'?'alert_event_id':key==='live_alert'?'live_alert_event_id':`${key}_id`) as keyof Incident]?'Linked':'Source removed; saved context'}</small></div>)}{!Object.keys(selected.context).length&&<p>Manual incident without linked context.</p>}<p className="analytics-note">Created: {new Date(selected.created_at).toLocaleString()} / Updated: {new Date(selected.updated_at).toLocaleString()}</p><button disabled={busy} onClick={()=>{if(window.confirm('Permanently delete this incident?'))void run(async()=>{await operationsApi(`/incidents/${selected.id}`,'DELETE');setSelected(null)})}}>Delete incident</button></section>}
  </div>
}
function Choice({label,value,options,onChange}:{label:string;value:string|null;options:Option[];onChange:(value:string|null)=>void}){return <label>{label}<select value={value??''} onChange={e=>onChange(e.target.value||null)}><option value="">None</option>{value&&!options.some(o=>o.id===value)&&<option value={value}>{value}</option>}{options.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</select></label>}
