import { useEffect, useRef, useState } from 'react'
import { FileVideo, Trash2, Upload } from 'lucide-react'
import { Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { ApiError, deleteVideo, listVideos, uploadVideo, type Video } from '../services/apiClient'
import { VideoPreview } from '../components/VideoPreview'

const formats = ['video/mp4', 'video/webm', 'video/quicktime']; const max = 100 * 1024 * 1024
export function VideosPage() { const [file, setFile] = useState<File | null>(null); const [videos, setVideos] = useState<Video[]>([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const input = useRef<HTMLInputElement>(null); const load = async () => { try { setVideos(await listVideos()) } catch { setError('Unable to load your video library.') } }; useEffect(() => { void load() }, []); const select = (f: File | undefined) => { if (!f || !formats.includes(f.type) || !f.size || f.size > max) { setError('Choose a non-empty MP4, WebM, or MOV file under 100 MB.'); setFile(null); return }; setError(''); setFile(f) }; const submit = async () => { if (!file) return; setLoading(true); try { const uploaded = await uploadVideo(file); setVideos(v => [uploaded, ...v]); setFile(null) } catch (e) { setError(e instanceof ApiError ? e.message : 'Upload failed.') } finally { setLoading(false) } }; const remove = async (id: string) => { if (window.confirm('Delete this uploaded video and its stored file?')) { await deleteVideo(id); setVideos(v => v.filter(x => x.id !== id)) } }
return <div className="page"><div className="page-heading"><p className="eyebrow">VIDEO ANALYSIS</p><h1>Upload video for person detection</h1><p>Anonymous person detections from sampled frames; no identities or tracking.</p></div><section className="card upload-zone"><Upload/><h2>Drop a video here</h2><p>MP4, WebM, or MOV · maximum 100 MB</p><input ref={input} aria-label="Choose video file" type="file" hidden onChange={e => select(e.target.files?.[0])}/><button className="primary" onClick={() => input.current?.click()}>Choose video</button>{file && <button className="primary" disabled={loading} onClick={submit}>{loading ? 'Analyzing…' : `Upload ${file.name}`}</button>}{error && <p role="alert">{error}</p>}</section><section className="video-library"><h2>Your video library</h2>{videos.map(video => <article className="card video-row" key={video.id}><FileVideo/><div><h3>{video.original_filename}</h3>{video.detection_summary && <><h4>Person Detection</h4><p>{video.detection_summary.total_person_detections} total person detections — not unique people, attendance, or crowd size.</p><p>Model {video.detection_summary.model}; confidence {video.detection_summary.confidence_threshold}; stride {video.detection_summary.frame_stride}</p><p>{video.detection_summary.sampled_frames_processed} sampled frames; {video.detection_summary.frames_with_people} with people; maximum {video.detection_summary.maximum_persons_in_sampled_frame}; average {video.detection_summary.average_persons_per_sampled_frame.toFixed(1)}</p>{video.detection_frames && <ResponsiveContainer width="100%" height={150}><LineChart data={video.detection_frames}><XAxis dataKey="frame_index"/><YAxis/><Tooltip/><Line dataKey="person_count" stroke="#2dd4bf"/></LineChart></ResponsiveContainer>}{video.has_annotated_preview && <VideoPreview videoId={video.id}/>}</>}{video.error_message && <p role="alert">{video.error_message}</p>}</div><button aria-label={`Delete ${video.original_filename}`} onClick={() => void remove(video.id)}><Trash2/></button></article>)}</section></div> }
